apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9002
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: BP_LIVE_RELOAD_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: POLAR_CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://polar-postgres/polardb_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://polar-postgres/polardb_order
